### ISSUE TITLE
Add listing upload image field related issue in Safari browser

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2217]
https://secure.helpscout.net/conversation/2020117295/36080/
https://secure.helpscout.net/conversation/2020072858/36077?folderId=3812058

possible fix: 
```
 body.geodir-page-add .bsui input {
    position: initial !important;
}
```

**Comment by kprajapatii** [comment]
Not able to reproduce, just assign me if you see new customer with similar issue.

@1naveengiri

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2320638439/46032?folderId=3812058
https://secure.helpscout.net/conversation/2315121094/45832?folderId=3812058

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2404545747/48568?folderId=3812058

**Comment by Stiofan** [comment]
Hopefully this is fixed in latest AUI, if not please reopen.

**Comment by 1naveengiri** [comment]
@Stiofan  I can still reproduce it even after the latest plugin update.
https://secure.helpscout.net/conversation/2404545747/48568/

**Comment by Stiofan** [comment]
@1naveengiri i can't replicate.  Please let me know if anyone else reports this.

**Comment by Stiofan** [comment]
was able to replicate once i updated safari, the fix was only applying to BS style and not legacy, I have added a fix in AUI.

**Comment by 1naveengiri** [comment]
`
body.geodir-page-add input[type="file"] {
   position: initial !important;
}`

https://secure.helpscout.net/conversation/2757515598/62506
