### ISSUE TITLE
Location Select does not work with tap, only click

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#584]
The location switcher/near field does not work with the trackpad 'tap', only with the harder 'click'.

**Comment by Stiofan** [comment]
not sure what u mean here, can u give an example?

**Comment by alexrollin** [comment]
tap as in soft tap on trackpad, not CLICK hard
It is a differentiation that is used in mobile coding.

**Comment by alexrollin** [comment]
Right, a light tap (touchstart?) doesn't work for me on desktop.
I have to press the touchpad down and on release it will select the item.

On the search button, for example, a tap will work and I don't have to click.

**Comment by Stiofan** [comment]
@kprajapatii did u manage to replicate this?

**Comment by kprajapatii** [comment]
I have checked with WIN7 + Chrome but can't replicate.
There are some known issues:
https://stackoverflow.com/questions/22039356/google-chrome-translate-all-touch-events-to-click-events
https://www.w3schools.com/jsref/event_touchstart.asp

I will check this and will ask @alexrollin to confirm, because he only replicating this.

**Comment by alexrollin** [comment]
This is an issue on Win10. 
I can replicate it every day.

**Comment by alexrollin** [comment]
Another win10 user noticed it too
https://wpgeodirectory.com/support/topic/neighbourhoods-2/#post-482287

**Comment by Stiofan** [comment]
This should be fixed in next release, test fix here: https://jsfiddle.net/34wjguro/2/ 
you should see alert 'touch' and then alert 'click'

**Comment by alexrollin** [comment]
This is still not fixed.
https://wpgeodirectory.com/support/topic/search-auto-suggest-soft-click-on-touchpad-not-working/#post-488419

**Comment by alexrollin** [comment]
Still not fixed
https://wpgeodirectory.com/support/topic/unable-to-select-autocomplete-location-option/#post-507997

**Comment by alexrollin** [comment]
Updated:

To recreate

On win10 with chrome, using notebook w touchpad 
In win10 settings, set Tap for click (this is a windows setting)
Go to https://wpgeo.directory/supreme-directory/
Place cursor in the near field
Wait for suggestions
'Tap' (do not click) on a suggestion
The suggestion will disappear, but suggestion is not placed into field
Select field again (focus)
Suggestions appear
'Click' (not tap) on suggestion and the suggestion will be placed in the near field.

**Comment by alexrollin** [comment]
win10
![image](https://user-images.githubusercontent.com/114659/65033537-7d51e280-d945-11e9-819f-df8f54ecf305.png)

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodir_location_manager-v2/pull/104/commits/31976b086f6df328ded0cbcf2d341c192170e25d
