### ISSUE TITLE
API - Search by location 

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#840]
https://wpgeodirectory.com/support/topic/api-v1-have-latitude-and-longitude-param-but-not-v2/#post-495620

after implementing this the endpoint will be like &latitude=XXXXX&longitude=XXXXX&order_by=XXXXX

**Comment by alexrollin** [comment]
This is for 'near search by api'

https://wpgeodirectory.com/support/topic/listings-near-me-2/#post-512608

**Comment by Stiofan** [comment]
More requests https://wpgeodirectory.com/support/topic/listings-search/

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodirectory/pull/980/commits/cb6809136a8a402ed892e325524b28cd75ffdd1b
https://github.com/AyeCode/geodir_advance_search_filters-v2/pull/46/commits/6735dd3a00b5a7c75f304ad077783311d00495d1
https://github.com/AyeCode/geodir_location_manager-v2/commit/c5b8d2719f2b94a0dee54af93d96397efa9254a6

Example:
By GPS
&latitude=XXXXX&longitude=XXXXX

OR by IP

&ip=xxx.xxx.xxx.xxx

OR address

&near=My Address

OR near me

&near=me

In all above cases following parameters will work

&orderby=distance
&order=asc or desc
&distance=xxx or it will take default from settings

**Comment by ThomLS** [comment]
Still doesn't work?{"code":"rest_invalid_param","message":"Ongeldige parameter(s): orderby","data":{"status":400,"params":{"orderby":"orderby is niet \u00e9\u00e9n van post_date_desc."}}}

**Comment by kprajapatii** [comment]
Hello @ThomLS,

Please contact us via https://wpgeodirectory.com/support/ so we can assist you.

**Comment by ThomLS** [comment]
> Hello @ThomLS,
> 
> Please contact us via https://wpgeodirectory.com/support/ so we can assist you.

Already did. :)
